name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  dockerimage_tag: ${{ github.sha }}
  dockerimage_name: tsungmnli/timer-fe

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ready to use Docker (1/4) - Create Metadata
        id: meta
        uses: docker/metadata-action@5.7.0
        with:
          images: |
            ${{ env.dockerimage_name }}
          tags: |
            ${{ env.dockerimage_tag }}
          flavor: |
            latest=true

      - name: Ready to use Docker (2/4) - Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Ready to use Docker (3/4) - Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ready to use Docker (4/4) - Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Import Config Repository
        uses: actions/checkout@v4
        with:
          repository: chunzhi23/timer-config
          ref: main
          token: ${{ secrets.ACTION_TOKEN }}
          path: timer-config

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Apply Generated Image to Config Repository
        run: |
          cd timer-config/overlays/prod/fe/
          kustomize edit set image ${{ env.dockerimage_name }}:${{ env.dockerimage_tag }}
          cat kustomization.yaml

      - name: Push Modified Config Repository
        run: |
          cd timer-config
          git config --global user.email "lzhongm05@gmail.com"
          git config --global user.name "chunzhi23"
          git commit -am "Update image tag"
          git push -u origin main
